title: Sex and Gender Wikipedia Guide
description: Guide to wikipedia on sex and gender issues
theme: just-the-docs

url: https://witchspace.github.io/sexandgenderwiki

aux_links:
  Template Repository: https://github.com/witchspace/sexandgenderwiki
